In [1]:
import numpy as np

l = [1, 2, 3, 4, 5]
a = np.array(l)
print(a)

[1 2 3 4 5]


In [2]:
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# write a code that creates a 2x4 numbers
l = [[1, 2, 3, 4], [5, 6, 7, 8]]
a = np.array(l)
print(a.shape)

(2, 4)


In [4]:
# numpy libraries
# np.array.random.randint (1-10) uniform distribution
# np.array.random.rand (0-1) uniform distribution
a = np.random.randint(1, 10, (3, 3))
a

array([[9, 1, 3],
       [8, 8, 1],
       [4, 8, 6]])

In [5]:
a = np.random.rand(20)
a

array([0.7855878 , 0.47185206, 0.70111046, 0.30918366, 0.12663084,
       0.73851776, 0.58886559, 0.35443829, 0.11801183, 0.32620846,
       0.33189385, 0.59985371, 0.69521193, 0.93491442, 0.49948688,
       0.02668406, 0.79939608, 0.41778074, 0.36507342, 0.22476031])

In [6]:
a= np.random.rand(3,3)
a

array([[0.48192358, 0.87267493, 0.90504608],
       [0.37555354, 0.53045579, 0.85699536],
       [0.10713058, 0.81496225, 0.1193295 ]])

In [7]:
a = np.random.randint(1, 50)
a

43

In [8]:
# eqally spaced numbers useful in loops
a = np.arange(1, 50)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [9]:
# make a 3x3 matrix with 0s
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [10]:
x = np.ones(7)
x

array([1., 1., 1., 1., 1., 1., 1.])

In [11]:
x = np.zeros((7,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
"""write a code that takes in a positive integer "x" from the user 
and creates a 1x10 array with random nubers ranging from 0 to "x"
"""

x = int(input("Enter a positive integer: "))

import numpy as np

# 0 to x will be excluded so we will use x+1
array = np.random.randint(0,x+1,(1,10))

print(array)


[[3 1 2 1 0 3 4 3 1 0]]


In [13]:
# addition in numpy arrays is associative
x = np.arange(1, 10)
y = np.arange(1, 10)
x+y

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
x ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
x=np.exp(y)
print(x)

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [16]:
sqrt = np.sqrt(x)
print(sqrt)

[ 1.64872127  2.71828183  4.48168907  7.3890561  12.18249396 20.08553692
 33.11545196 54.59815003 90.0171313 ]


In [17]:
"""given the x and y coordinates as a numpy array, write a code that calculates the distance between the points
    using euclidean distance formula
"""

x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 2, 3, 4, 5])

# distance formula
# sqrt((x2-x1)^2 + (y2-y1)^2)
print(np.sqrt((x[1:]-x[:-1])**2 + (y[1:]-y[:-1])**2))

[1.41421356 1.41421356 1.41421356 1.41421356]


In [18]:
x = np.array([[2,30,20,-2,-4],
              [3,5,6,7,8],
              [9,10,11,12,13],
              [14,15,16,17,18]])
x[-1] = 0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13],
       [ 0,  0,  0,  0,  0]])

In [19]:
"""replace negative elements with 0 in matrix (use subseting), positive with -2
"""
#  In the following matrix, replace negative elements by O and replace odd elements with -2
x = [[2, 30 ,20, -2, -4],
    [3,4 ,40 ,-3 ,-2],
    [-3 ,4 ,-6 ,90 ,10],
    [25 ,45 ,34 ,22 ,12],
    [13 ,24, 22 ,32 ,37]]
x  = np.array(x)
x[x<0] = 0

x[x%2 != 0] = -2

print(x)

[[ 2 30 20  0  0]
 [-2  4 40  0  0]
 [ 0  4  0 90 10]
 [-2 -2 34 22 12]
 [-2 24 22 32 -2]]


In [20]:
# A porfolio contains a collection of securities such as stocks, bonds and ETFS. Define a dataframe named •portfolio_df that holds 3 different stock ticker symbols. number of shares, and price
# per share (feel free to choose any Stocks)
# Calculate the total value Of the porfolio inchJding all Stocks

import pandas as pd

portfolio_df = pd.DataFrame({'Ticker': ['AAPL', 'MSFT', 'AMZN'],'Shares': [100, 200, 300],'Price': [200, 300, 400]})

print(portfolio_df)

print(portfolio_df['Shares']*portfolio_df['Price'])

print(portfolio_df['Shares']*portfolio_df['Price'].sum())

  Ticker  Shares  Price
0   AAPL     100    200
1   MSFT     200    300
2   AMZN     300    400
0     20000
1     60000
2    120000
dtype: int64
0     90000
1    180000
2    270000
Name: Shares, dtype: int64


In [21]:
# Write a code that uses Pandas to read tabular US retirement data
# You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

import pandas as pd

us_retirement_data = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')[0]

# Print the first 5 rows of the data
print(us_retirement_data.head())

    Year of birth              Age
0  1937 and prior               65
1            1938  65 and 2 months
2            1939  65 and 4 months
3            1940  65 and 6 months
4            1941  65 and 8 months


In [22]:
bank_client_df = pd.DataFrame({' Bank client ID' : [111, 222, 333, 444],
'Bank Client Name' : ['Chanel', 'Steve','Mitch','Ryan'],
'Net worth [$]' : [3500, 29000, 10000, 2000],
'Years with bank' : [3, 4, 9,5]})
print(bank_client_df)

# Using DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000
# What is the combined networth for all customers with 5000+ networth?
print(bank_client_df[bank_client_df['Net worth [$]'] > 5000].sum()['Net worth [$]'])

    Bank client ID Bank Client Name  Net worth [$]  Years with bank
0              111           Chanel           3500                3
1              222            Steve          29000                4
2              333            Mitch          10000                9
3              444             Ryan           2000                5
39000


In [23]:
# Define a function that increases all clients networth (stocks) by a fixed value of (for simplicity sake)
def networth_update(blance):
    return blance*1.2 #assume that stock prices increase by 20%

bank_client_df['Net worth [$]'].apply(lambda x : x*1.2)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [24]:
# order by networth
bank_client_df.sort_values('Net worth [$]')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
3              444             Ryan           2000                5
0              111           Chanel           3500                3
2              333            Mitch          10000                9
1              222            Steve          29000                4

In [25]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4, 5, 6, 7])

# contatenate dataframes

pd.concat([df1, df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [30]:
# Define a dataframe named 'Bank df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5
# Assume that the bank got 5 new clients, define another dataframe named 'Bank_df 2' that contains a new clients with IDs =  6, 7, 8, 9, 10
# Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers)
# Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
# Merge client names and their newly added salary information using the 'Bank Client ID'
# Let's assume that you became a new dient to the bank
# Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
# Add this new dataframe to the original dataframe 'bank_df_all'.

bank_df_1 = pd.DataFrame({'Client ID': [1, 2, 3, 4, 5], 'First Name': ['John', 'Jane', 'Joe', 'Jessica', 'Jacob'], 'Last Name': ['Doe', 'Smith', 'Johnson', 'Williams',
                                                                                                                                 'Brown']})
bank_df_2 = pd.DataFrame({'Client ID': [6, 7, 8, 9, 10], 'First Name': ['Jake', 'Jill', 'Jacob', 'Jessica', 'Jacob'], 'Last Name': ['Doe', 'Smith', 'Johnson', 'Williams',
                                                                                                                                    'Brown']})

# Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers)
data = {'Client ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'Annual Salary': [10000, 20000, 30000, 40000, 50000, 60000, 70000, 80000, 90000,100000]}
bank_df_salary = pd.DataFrame(data)

# Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
bank_df_all = pd.concat([bank_df_1,bank_df_2], axis=0)

# Merge client names and their newly added salary information using the 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all,bank_df_salary,on='Client ID', how='left')

# Let's assume that you became a new client to the bank
# Define a new DataFrame that contains your information such as client ID (choose 11), first name ('YourFirstName'), last name ('YourLastName'), and annual salary (120000).
data = {'Client ID': [11], 'First Name': ['YourFirstName'], 'Last Name': ['YourLastName'], 'Annual Salary': [120000]}
new_client = pd.DataFrame(data)

# Add this new dataframe to the original dataframe 'bank_df_all'.
bank_df_all = pd.concat([bank_df_all,new_client], axis=0)

bank_df_all


Client ID     First Name     Last Name  Annual Salary
0          1           John           Doe          10000
1          2           Jane         Smith          20000
2          3            Joe       Johnson          30000
3          4        Jessica      Williams          40000
4          5          Jacob         Brown          50000
5          6           Jake           Doe          60000
6          7           Jill         Smith          70000
7          8          Jacob       Johnson          80000
8          9        Jessica      Williams          90000
9         10          Jacob         Brown         100000
0         11  YourFirstName  YourLastName         120000