In [9]:
from sklearn.datasets import fetch_openml
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Load the Fashion-MNIST dataset
X, y = fetch_openml('Fashion-MNIST', version=1, return_X_y=True)
# The Fashion-MNIST dataset is a collection
# of  Zalando's  article images. It contains 60,000 images for the training set and 10,000 images for
# the test set data (we will discuss the test and training datasets along with the validation dataset
# later). These are 28 x 28 grayscale images and belong to the labels of 10 different classes.

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Normalize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create a MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(100, 100), max_iter=20, alpha=0.0001,
                    solver='adam', verbose=10, random_state=1,
                    learning_rate_init=0.001)

# print classes found in the dataset
print('Classes:', np.unique(y))

# Fit the model to the training data
mlp.fit(X_train, y_train)

# Make predictions on the test data
predictions = mlp.predict(X_test)

acc = accuracy_score(y_test, predictions)
print('Accuracy: {:.2f}%'.format(acc * 100))


# Calculate the confusion matrix
cm = confusion_matrix(y_test, predictions)
print(cm)

Classes: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
Iteration 1, loss = 0.50119556
Iteration 2, loss = 0.34310053
Iteration 3, loss = 0.30126178
Iteration 4, loss = 0.27104769
Iteration 5, loss = 0.25187250
Iteration 6, loss = 0.23397156
Iteration 7, loss = 0.21657527
Iteration 8, loss = 0.20283371
Iteration 9, loss = 0.19073292
Iteration 10, loss = 0.18142667
Iteration 11, loss = 0.16795125
Iteration 12, loss = 0.15390801
Iteration 13, loss = 0.14608573
Iteration 14, loss = 0.13943018
Iteration 15, loss = 0.12955005
Iteration 16, loss = 0.12229597
Iteration 17, loss = 0.11568305
Iteration 18, loss = 0.11174523
Iteration 19, loss = 0.10556216
Iteration 20, loss = 0.09538746
Accuracy: 88.76%
[[1217    2   14   23    2    1  154    0    7    0]
 [   3 1350    1   16    4    0    4    0    0    0]
 [  28    2 1129    9   77    1  122    0    2    0]
 [  75    9   10 1249   29    0   44    0    0    0]
 [   6    6  146   46 1052    0  139    0    3    0]
 [   1    0    0    0    0 1315    0

In [ ]:
import os
import cv2
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Define a function to load and preprocess the images
def load_images(path):
    """ Load images from the given path , classify them as normal or covid and resize them to 150x150 pixels.
    then convert them to grayscale and return images(x) and labels(y) as numpy arrays."""
    images = []
    labels = []
    for folder in os.listdir(path):
        label = 0 if folder == 'normal' else 1
        for file in os.listdir(os.path.join(path, folder)):
            img = cv2.imread(os.path.join(path, folder, file))
            # resize the image to 150x150 pixels
            img = cv2.resize(img, (150, 150))
            # convert to grayscale
            img = img.astype('float32') / 255
            images.append(img)
            labels.append(label)
    return np.array(images), np.array(labels)

# Load the images
X, y = load_images('dataset')

# Flatten the images
X = X.reshape(X.shape[0], -1)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(X_test,'\n' ,y_test)

# Create a MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

# Fit the model to the training data
mlp.fit(X_train, y_train)

# Make predictions on the test data
predictions = mlp.predict(X_test)

acc = accuracy_score(y_test, predictions)
print('Accuracy: {:.2f}%'.format(acc * 100))

# print the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predictions)
print(cm)

[[0.01176471 0.01176471 0.01176471 ... 0.00392157 0.00392157 0.00392157]
 [0.26666668 0.26666668 0.26666668 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.99607843 0.99607843 0.99607843 ... 0.42745098 0.4117647  0.40392157]
 [0.4392157  0.4392157  0.4392157  ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.03921569 0.03921569 0.03921569]] 
 [1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1]
Accuracy: 94.74%
[[ 3  0]
 [ 1 15]]
