In [11]:
import numpy as np

def parse_input(input_string):
    # Split the string into a list of strings, then convert each string to a float
    numbers = [float(num_str) for num_str in input_string.split('\n') if num_str]

    # Convert the list of numbers to a numpy array
    return np.array(numbers)

# Test the function with your input
Y = """
1.95
2.90
0.72
0.81
1.09
1.22
1.02
1.93
0.64
2.08
1.98
1.90
8.56
4.49
8.49
6.17
7.54
6.36
7.63
7.78
10.15
6.88"""
X1="""
1.31
1.55
0.99
0.99
1.01
1.09
1.08
1.27
0.99
1.34
1.30
1.33
1.86
1.58
1.97
1.80
1.75
1.72
1.68
1.75
2.19
1.73"""
X2="""
1.07
1.49
0.84
0.83
0.90
0.93
0.90
1.08
0.85
1.13
1.10
1.10
1.47
1.34
1.59
1.56
1.58
1.43
1.57
1.59
1.86
1.67"""
X3="""
0.44
0.53
0.34
0.34
0.36
0.42
0.40
0.44
0.36
0.45
0.45
0.48
0.60
0.52
0.67
0.66
0.63
0.64
0.72
0.68
0.75
0.64"""
X4="""
0.75
0.90
0.57
0.54
0.64
0.61
0.51
0.77
0.56
0.77
0.76
0.77
1.01
0.95
1.20
1.02
1.09
1.02
0.96
1.08
1.24
1.14"""
X5="""
0.35
0.47
0.32
0.27
0.30
0.31
0.31
0.34
0.29
0.37
0.38
0.38
0.65
0.50
0.59
0.59
0.59
0.63
0.68
0.62
0.72
0.55"""

Y,X1,X2,X3,X4,X5 = parse_input(Y),parse_input(X1),parse_input(X2),parse_input(X3),parse_input(X4),parse_input(X5)


In [15]:
import numpy as np

def learn_coefficients(Y, *args):
    # Ensure that all inputs are numpy arrays and concatenate them
    X = np.column_stack((np.ones(len(args[0])), *[np.array(arg) for arg in args]))
    
    # X
    print('X matrix:\n',X)
    # Y
    print('Y matrix:',Y)
    
    # Compute the coefficients using the least squares estimating equations
    # theta = inv(X'X)X'Y
    theta = np.linalg.inv(X.T @ X) @ X.T @ Y

    return theta
theta = learn_coefficients(Y,X1, X2, X3, X4, X5)
print(f"Learned coefficients: {theta}")

# predict given X1 and X2
# X1 = np.array([35])
# X2 = np.array([250])
# y_pred = np.array([1, *X1, *X2]) @ theta
# print(f"Predicted value: {y_pred}")

X matrix:
 [[1.   1.31 1.07 0.44 0.75 0.35]
 [1.   1.55 1.49 0.53 0.9  0.47]
 [1.   0.99 0.84 0.34 0.57 0.32]
 [1.   0.99 0.83 0.34 0.54 0.27]
 [1.   1.01 0.9  0.36 0.64 0.3 ]
 [1.   1.09 0.93 0.42 0.61 0.31]
 [1.   1.08 0.9  0.4  0.51 0.31]
 [1.   1.27 1.08 0.44 0.77 0.34]
 [1.   0.99 0.85 0.36 0.56 0.29]
 [1.   1.34 1.13 0.45 0.77 0.37]
 [1.   1.3  1.1  0.45 0.76 0.38]
 [1.   1.33 1.1  0.48 0.77 0.38]
 [1.   1.86 1.47 0.6  1.01 0.65]
 [1.   1.58 1.34 0.52 0.95 0.5 ]
 [1.   1.97 1.59 0.67 1.2  0.59]
 [1.   1.8  1.56 0.66 1.02 0.59]
 [1.   1.75 1.58 0.63 1.09 0.59]
 [1.   1.72 1.43 0.64 1.02 0.63]
 [1.   1.68 1.57 0.72 0.96 0.68]
 [1.   1.75 1.59 0.68 1.08 0.62]
 [1.   2.19 1.86 0.75 1.24 0.72]
 [1.   1.73 1.67 0.64 1.14 0.55]]
Y matrix: [ 1.95  2.9   0.72  0.81  1.09  1.22  1.02  1.93  0.64  2.08  1.98  1.9
  8.56  4.49  8.49  6.17  7.54  6.36  7.63  7.78 10.15  6.88]
Learned coefficients: [-6.44433549  1.77194873 -3.65729301  2.41108257  5.39665736 14.62052654]


# 12.1
```
X matrix:
 [[ 1.    1.32  1.15]
 [ 1.    2.69  3.4 ]
 [ 1.    3.56  4.1 ]
 [ 1.    4.41  8.75]
 [ 1.    5.35 14.82]
 [ 1.    6.2  15.15]
 [ 1.    7.12 15.32]
 [ 1.    8.87 18.18]
 [ 1.    9.8  35.19]
 [ 1.   10.65 40.4 ]]
Y matrix: [  6.4   15.05  18.75  30.25  44.85  48.94  51.55  61.5  100.44 111.42]
Learned coefficients: [0.57998789 2.71223758 2.04970749]```

# 12.4
```
X matrix:
 [[  1.  42. 272.]
 [  1.  33. 226.]
 [  1.  33. 259.]
 [  1.  45. 292.]
 [  1.  39. 311.]
 [  1.  36. 183.]
 [  1.  32. 173.]
 [  1.  41. 236.]
 [  1.  40. 230.]
 [  1.  38. 235.]]
Y matrix: [ 95.  77.  80. 100.  97.  70.  50.  80.  92.  84.]
Learned coefficients: [-22.99316393   1.39567292   0.21761341]
Predicted value: 80.25873982020002
```

In [ ]:
import numpy as np

def learn_coefficients_type2(Y, v):
    # Ensure that v and Y are numpy arrays
    v = np.array(v)
    Y = np.array(Y)

    # Create a matrix X where the first column is filled with ones,
    # the second column is filled with v, and the third column is filled with v^2
    X = np.column_stack((np.ones(len(v)), v, v**2))
    
    # remove the 'e' notation
    np.set_printoptions(suppress=True)
    print("X matrix:\n", X)
    print("Y matrix:", Y)

    # Compute the coefficients using the normal equation
    # theta = inv(X'X)X'Y
    theta = np.linalg.inv(X.T @ X) @ X.T @ Y

    return theta

# Test the function with some data
d="""16
26
41
62
88
119
"""
v="""35
50
65
80
95
110
"""
d,v = parse_input(d), parse_input(v)
theta = learn_coefficients_type2(d, v)
print("Learned coefficients:", theta)

# predict given v
v = np.array([70])
y_pred = np.array([1, *v, *v**2]) @ theta
print(f"Predicted value: {y_pred}")

# 12.6
```
X matrix:
 [[    1.    35.  1225.]
 [    1.    50.  2500.]
 [    1.    65.  4225.]
 [    1.    80.  6400.]
 [    1.    95.  9025.]
 [    1.   110. 12100.]]
Y matrix: [ 16.  26.  41.  62.  88. 119.]
Learned coefficients: [13.35873016 -0.33944444  0.0118254 ]
Predicted value: 47.54206349206198
```

# 12.11
```
X matrix:
 [[1.   1.31 1.07 0.44 0.75 0.35]
 [1.   1.55 1.49 0.53 0.9  0.47]
 [1.   0.99 0.84 0.34 0.57 0.32]
 [1.   0.99 0.83 0.34 0.54 0.27]
 [1.   1.01 0.9  0.36 0.64 0.3 ]
 [1.   1.09 0.93 0.42 0.61 0.31]
 [1.   1.08 0.9  0.4  0.51 0.31]
 [1.   1.27 1.08 0.44 0.77 0.34]
 [1.   0.99 0.85 0.36 0.56 0.29]
 [1.   1.34 1.13 0.45 0.77 0.37]
 [1.   1.3  1.1  0.45 0.76 0.38]
 [1.   1.33 1.1  0.48 0.77 0.38]
 [1.   1.86 1.47 0.6  1.01 0.65]
 [1.   1.58 1.34 0.52 0.95 0.5 ]
 [1.   1.97 1.59 0.67 1.2  0.59]
 [1.   1.8  1.56 0.66 1.02 0.59]
 [1.   1.75 1.58 0.63 1.09 0.59]
 [1.   1.72 1.43 0.64 1.02 0.63]
 [1.   1.68 1.57 0.72 0.96 0.68]
 [1.   1.75 1.59 0.68 1.08 0.62]
 [1.   2.19 1.86 0.75 1.24 0.72]
 [1.   1.73 1.67 0.64 1.14 0.55]]
Y matrix: [ 1.95  2.9   0.72  0.81  1.09  1.22  1.02  1.93  0.64  2.08  1.98  1.9
  8.56  4.49  8.49  6.17  7.54  6.36  7.63  7.78 10.15  6.88]
Learned coefficients: [-6.44433549  1.77194873 -3.65729301  2.41108257  5.39665736 14.62052654]
 ```

# 12.14
```
X matrix:
 [[  1.    69.   125.    59.    55.66]
 [  1.    57.   131.    31.75  63.97]
 [  1.    77.   141.    80.5   45.32]
 [  1.    81.   122.    75.    46.67]
 [  1.     0.   141.    49.    41.21]
 [  1.    53.   152.    49.35  43.83]
 [  1.    77.   141.    60.75  41.61]
 [  1.    76.   132.    41.25  64.57]
 [  1.    65.   157.    50.75  42.41]
 [  1.    97.   166.    32.25  57.95]
 [  1.    76.   141.    54.5   57.9 ]]
Y matrix: [410. 569. 425. 344. 324. 505. 235. 501. 400. 584. 434.]
Learned coefficients: [-884.66702638   -0.83813133    4.9066099     1.33112943   11.93128758]
 ```